### PR TITLE
11.0 mig l10n fr state

### PR DESCRIPTION
**Pull request by njeudy**
Migrate to V11 and python 3

### CODE REVIEW

**Comment by njeudy** [comment]
needed by #131

**Comment by legalsylvain** [comment]
Hi @njeudy. Same remarks here as #131 about yml file.
kind regards.

**Comment by njeudy** [comment]
Ok will check this .. I should remove all yml file ? deprecated in V11 ?

**Comment by njeudy** [comment]
@legalsylvain @pedrobaeza I the other PR, if it is ok for you I prefer migrate yml to xml in an other PR. I will do the job for sure, but have some other priority module to migrate. (edi, ....)

**Comment by pedrobaeza** [comment]
I don't have a special preference. I think you can put a note in roadmap saying that "YML data should be migrated to XML", but it's enough, as the module works as is.

**Comment by njeudy** [comment]
@legalsylvain @pedrobaeza Ok done and rebase to lastest 11.0 branch.

**Comment by legalsylvain** [comment]
OK. Thanks.
Well, not sure that it's the OCA norm to add it as author, when there are no changes or trivial changes due to migration.

Otherwise, LGTM.

**Review by alexis-via — APPROVED** [review]

**Pull request merged**
