### PR TITLE
[MIG][12.0] l10n_fr_siren_lookup

### PR DESCRIPTION
**Pull request by remi-filament**
Port Siren Lookup module from v10.0 to v12.0, updating also SIRENE API from v1 to v3

### CODE REVIEW

**Comment by alexis-via** [comment]
On https://public.opendatasoft.com/explore/dataset/sirene_v3/table/ it says "Base Sirene v3 (non maintenue à partir du 1er octobre 2021) ". In the "Information" tab, they say "Ce jeu ne sera plus maintenu à partir du 1er Octobre 2021. Il est remplacé par le jeu recherche 'economicref[tiret]france[tiret]sirene[tiret]v3' en remplaçant [tiret] par -."
The link to the new API: https://public.opendatasoft.com/explore/dataset/economicref-france-sirene-v3/information/

**Comment by remi-filament** [comment]
Thanks @alexis-via  I have just updated the source dataset accordingly.

I am wondering whether we could go further in integration of these data by :
- using pappers API instead (https://www.pappers.fr/api/documentation)  - it provides more information (in particular VAT ID which is missing here), but one need to create an account on the site to use it (for free)
- reusing parts from partner_autocomplete Odoo module (for autocompletion when entering partner instead of using wizard)

Let me know what you think about the above ?

**Comment by alexis-via** [comment]
Yes, i'm studying the different APIs and methods of integration in Odoo. I have already used your module. Maybe we could organise a call to confront our ideas (I have some availabilities this week).

**Comment by remi-filament** [comment]
Sure, this week I can only on Thursday afternoon (the 14th), would it be possible for you ?

**Comment by alexis-via** [comment]
OK for Thursday afternoon. I propose at 13h45 (I have another meeting at 14h30, so it can last up to 45 minutes, which should be more than enough). If it's not possible for you at 13h45, then I propose 16h30.
We can meet on this link (i make it public so that others can join if they wish):
meet.google.com/dfb-jsrk-yub

**Comment by remi-filament** [comment]
Thanks Alexis, maybe better 16h30 since I have a meeting on morning outside of office and not sure I can make it for 13h45.
Also, sorry to differ, but if we could meet on Jitsi instead of Google that would save me some headache from Google asking me to create an account...
We could meet here then : https://video.le-filament.com/EvolutionaryStrandsScreenSternly
Thanks !

**Comment by alexis-via** [comment]
OK for 16h30. You don't need any Google account to join a google meet.  But anyway, let's meet on your link.

**Comment by alexis-via** [comment]
pappers.fr may provide the VAT number, but, just like societe.com, they just compute it by adding the FR prefix + checksum. Exemple : lookup on societe.com or pappers.fr a company that is not subject to VAT (like an auto-entrepreneur for example) and you'll be very surprised to see that they display a VAT number for the company!!! So, I prefer to ignore this info than set a wrong info.

**Comment by alexis-via** [comment]
Now that it has been merged in v14, I propose to close this PR. If someone wants to backport the v14 code to v12, he should make another PR. Are you OK with my proposal @remi-filament ?

**Comment by remi-filament** [comment]
Fine with me, let me close this one.

**Pull request closed without merging**
