### PR TITLE
[14.0] dotfiles update needs manual intervention

### PR DESCRIPTION
**Pull request by sbidoul**
Dear maintainer,

After updating the dotfiles, `pre-commit run -a`
fails in a manner that cannot be resolved automatically.

Can you please have a look, fix and merge?

Thanks,

### CODE REVIEW

**Comment by legalsylvain** [comment]
Hi @sbidoul. 

hard-fixed by #298.
(Ref : #299 )

if you rebase, it should work.

kind regards.

**Comment by sbidoul** [comment]
> if you rebase, it should work.

Please do :) this message was generated by an automated script that I happened to with a github token of mine.

**Comment by legalsylvain** [comment]
@OCA-git-bot : you're so obsolete.

**Pull request merged**
