### PR TITLE
[14.0][MIG] Chorus Pro connector with Factur-X support

### PR DESCRIPTION
**Pull request by alexis-via**

### CODE REVIEW

**Comment by alexis-via** [comment]
This PR depends on tons of other v14 PRs. And I still have to make the PR for the migration of account_invoice_facturx (still some improvements to make on that module in my TODO list). I'll publish a list of all the PR we depend on very soon.

**Comment by aallouche** [comment]
Hello @alexis-via and @legalsylvain 
I noticed the csets from last weekend and I sent an email to Alexis.
On our side, we have an opportunity to work on a backport of this chorus pro integration for v13 and v11 in the next quarter.
I'd rather discuss this with you so we can get a common feature set including some changes (I think about oauth2 authentication via PISTE for instance).
Let me know!

**Review by qpeyramale — APPROVED** [review]

**Comment by sebastienbeau** [comment]
rebase PR

**Review by sebastienbeau — APPROVED** [review]
LGTM tested and code review

**Pull request merged**
