### PR TITLE
Revert merge of OCA/l10n-france#47 that broke both travis and runbot

### PR DESCRIPTION
**Pull request by lepistone**
#47 added a dependency on aeroo, which probably we don't want (see #59) and broke both travis and runbot builds on this branch.

I suggest we revert quickly as this affects all other pull requests, and then we can discuss with @alexis-via if he wants to submit another version of the module.

Thanks to all!

### CODE REVIEW

**Comment by Garamotte** [comment]
Travis build red because of a missing dependency (`account_direct_debit` from `bank-payment` repo).
Runbot build yellow because of a deprecated module (`base_contact` from `partner-contact` repo)

**Comment by lepistone** [comment]
I investigated: the travis build is red because we need to merge https://github.com/OCA/l10n-france/pull/57 to handle dependencies. After (OCA/maintainer-quality-tools#289 we need to use oca_dependencies.txt instead of cloning manually).

This as #57 will conflict. I suggest we do this revert now, and then I'll rebase and fix #57 to get our green build.

Thanks!

**Comment by damdam-s** [comment]
:+1: revert ok

**Comment by Garamotte** [comment]
:+1:

**Comment by tafaRU** [comment]
:+1:

**Comment by fclementic2c** [comment]
I cannot give a technical opinion. 
On the functional aspect, the feature is interesting since EBP est an accounting software widely used in France.
But the most important is that do not break everything. 
I agree to remove it if it cannot be fixed. @alexis-via Can you give your position on this please ? thx

**Comment by yvaucher** [comment]
:+1:

**Comment by lepistone** [comment]
@alexis-via I was in a hurry to revert to fix the CI, but you're of course very welcome to propose again your work. Thanks!

**Comment by alexis-via** [comment]
I had a technical problem with my private emails (on which I receive these emails) during the last 5 days, and I wasn't notified of this PR. My private emails are working again this morning and I discover this PR today, and I am really NOT happy.

The module account_balance_ebp_csv_export has been in l10n-france for a long time (PR created in March 2015 and merged in v7 in August 2015, cf https://github.com/OCA/l10n-france/pull/19) and none of you ever made a remark on the PR at that time. And then, over the week-end, my hard work on this module is wiped out by a few guys that are not usual l10n-france contributors, but have commit rights on l10n-france. I can accept that from regular l10n-france contributors, but not from people that almost never contributed to l10n-france. This is a big lack of respect for the few guys that REALLY work on l10n-france, day after day, month after month, year after year, to try to propose a few useful modules to the community. And this module is one of the most useful module of l10n-france, because it's a module that allows French companies to do their "liasse fiscale" easily.

And, instead of wiping-out my work, it would have been more constructive to word and discuss on the related bug report created a few weeks ago by Alexandre Fayolle https://github.com/OCA/l10n-france/issues/59 Now that my work has been wiped-out, nobody will be motivated to work on on this bug report and find a proper solution (which should not be difficult by the way, we just need a report_txt module).

I'm not sure I'll continue to propose the modules I develop to OCA/l10n-france until this kind of things can happen from non-contributors to l10n-france. So, maybe Travis is now green, but you have probably lost one regular contributor of l10n-france.

Bye bye.

**Comment by lepistone** [comment]
Hi @alexis-via I am really sorry for that.

What happened is that friday on IRC #oca someone complained that pull requests on l10n-france were all red. As a core maintainer, I sometimes do this kind of things: make sure that CI works, PRs can be reviewed properly, keep an eye on maintainer-quality-tools. This is of course across all repositories.

So I traced the problem, and found that one PR, didn't know the previous history in v7 and so on. I just saw a self-merge that broke both travis and runbot.

In my mind, a quick revert could allow other people to have working CI on other PRs today, and then your one could be fixed. @fclementic2c was wiser than me suggesting to hang on and wait for your opinion. I really wanted to bring your work back later, without breaking all builds (and possibly without aeroo).

I'll answer on #59 and see if I can give a little help on that.

**Comment by alexis-via** [comment]
In fact, I initially submitted the module account_balance_ebp_csv_export on LP in this merge proposal: https://code.launchpad.net/~akretion-team/openerp-french-localization/account-balance-ebp-csv-export-70 which is dated September 2014. This merge proposal was rejected by Sebastien Beau in March 2015 when Sebastien moved it to Github... and then I was merged on github in August 2015. So the MP/PR was under review during 11 months, and during that time nobody said that he disagreed on the dependency on report_aeroo.

Other point: when this PR #19 for v7 was merged on github, Travis was green. So it's technically possible to have Travis green with a module that depends on report_aeroo.
Also : instead of wiping-out the full module, you could have set it installable=False in **openerp**.py. That would have made Travis green I guess and would have allowed an easy "come back" of the module later on.

**Comment by alexis-via** [comment]
As I explained in my previous comments, this module account_balance_ebp_csv_export that I developped has gone through an 11-month-long review process on this project and this PR has wiped it out in only 3 days. With this very hard experience, I figured out that it's too "dangerous/risky" for me to push my work in OCA/l10n-france. So I decided to move the module account_balance_ebp_csv_export to a new repository outside of the OCA where only contributors to the code will have direct commit access. This decision also applies on all the modules that I develop and that were under review for inclusion in OCA/l10n-france:
- l10n_fr_intrastat_product (DEB) and l10n_fr_intrastat_service (DES)
- l10n_fr_invoice_import
- l10n_fr_mis_reports (bilan et compte de résultat français)

That's why I closed the related PR today.
The new modules that I may develop in the future for the french localization will not be hosted in OCA/l10n-france either. But I decided to continue to maintain the modules currently hosted in OCA/l10n-france in OCA/l10n-france, so that users of the current modules will not be impacted by this decision and will not have to choose which repository to use.

I will decide in the coming days the name and location of the new repository and I will announce it here, so that users of account_balance_ebp_csv_export can continue to get the updates and fixes from the new repository.

**Comment by jgrandguillaume** [comment]
Dear @alexis-via ,

Please reconsider you decision. I can understand that you're angry about what happened, but @lepistone made a good decision reverting this PR. We can't let Travis red because all other contributors will then be blocked in their work. That was not attended to remove definitely this modules, but to allow people to continue to work with the needed CI tools.

Saying "_it's too dangerous/risky for me to push my work in OCA/l10n-france_" is a bit harsh compare to what happen. For the good of all, sometimes a contributor will face such a frustration, but all-in-all we all benefit having a common repo for all localizations. So please, don't take this personally and change your mind, continue to publish your excellent work under the OCA umbrella.

Maintaining the CI tools working properly is a priority for the good of all our contributors, I'm sure you can understand that.

Thanks for re-considering your decision.

Best regards,

Joël

**Comment by alexis-via** [comment]
I don't think that making travis green can justify the complete removal of a module like this, which is used in production by several companies (including Akretion by-the-way). Imagine a non-expert user that update his branch and the module just "disappear" !!! If the goal is really to make travis green "in emergency", putting installable=False in the module or some other simple change like this would probably be a solution "in emergency". Kicking the module out cannot be the right solution.

When this module account_balance_ebp_csv_export was merged in v7 in August 2015, Travis was green, cf my last comment on the PR https://github.com/OCA/l10n-france/pull/19
This shows that it's possible to have a green Travis with the module account_balance_ebp_csv_export in l10n-france. I agree that Travis needs to be green ; and to make Travis green, we need to fix the root cause of the problem (I guess it is somewhere in the Travis config file), and not remove the module !

When we find a bug in an OCA module, we don't remove the module from the OCA, we just fix the bug ! It is the same here !

**Comment by pedrobaeza** [comment]
@alexis-via, I also beg you to reconsider your decision. Everyone made mistakes, and the decision wasn't the best taken, but we are only at one PR of distance to solve it :wink: 

Let me know if I can help to bring again the module to the repo and solve the Travis issue.

**Comment by alexis-via** [comment]
@pedrobaeza
What I dislike a lot with the consequence of what took place here is that someone removed the module... but who will do the work to re-integrate the module ? Me again ? I am used to do most of the work on l10n-france, but here I don't want to do this work of re-integrating the module accout_balance_ebp_csv_export, or at least not alone and I don't want to take the lead on this.

I wrote the module accout_balance_ebp_csv_export and it works very well (Akretion France used it to do its annual fiscal declaration of its first and second fiscal year). For me, the dependency on report_aeroo is not a problem because I use report_aeroo in all my Odoo deployments. But I understand that it can be a problem for the OCA or that it can be a problem for other users. What I don't want is that someone removes the module from l10n-france and let me do all the work alone to re-integrate it. This time, it's just too much work for me and I don't want to do that work (or at least not alone).

But, now that the module has been removed, nobody is motivated to solve the bug #59 and work on the developpment of a "report_txt" module in the OCA. I don't want to develop this module report_txt myself because my OCA work pipeline is already full (and you will see in the coming days a big contribution from me to the OCA that kept me busy these last days^W nights) and I don't have experience on the reporting engines. But, if someone takes the lead on the development of a report_txt module following the clash that took place here, then I will reconsider my decision and I will adapt accout_balance_ebp_csv_export to use report_txt and re-submit it to OCA/l10n-france. But, if nothing happen, then I'll just move this module to a new home outside the OCA (and the 4 other modules with it... so that this module doesn't feel depressed because he is alone without some l10n_fr_\* friends with him).

**Comment by lepistone** [comment]
Hi @alexis-via.

I understand your frustration. To clarify: I like not having aeroo, but that's not a blocker. What I really want is a green build to allow others to work (that's what started it all on #oca). I also did #64 for the same reason (and now travis is green indeed).

So I am of course not asking you to work on a new reporting engine. Maybe we can get aeroo back just with some hack in `.travis.yml`. It works already on `7.0` I suppose? I'll try to give it a shot if I find the time.

**Comment by pedrobaeza** [comment]
I'll also check for fixing this for the shake of the good. Let's continue all together as the solid community we are!

**Comment by sebastienbeau** [comment]
Hi all, just to quick message to inform that I am working on a version of export without EBP code is here soon ready to be reviewed https://github.com/OCA/l10n-france/pull/68

**Comment by pedrobaeza** [comment]
Cool!

**Pull request merged**
