### PR TITLE
[12.0][l10n_fr_intrastat_product][ADD] fr_partner_vat to xls report

### PR DESCRIPTION
**Pull request by ivantodorovich**
For some companies it's usefull to have the partner's VAT number aswell.

@alexis-via

### CODE REVIEW

**Review by alexis-via — APPROVED** [review]

**Comment by legalsylvain** [comment]
@ivantodorovich could you rebase. There are conflicts. 
Thanks !

**Comment by ivantodorovich** [comment]
> @ivantodorovich could you rebase. There are conflicts.
> Thanks !

Done :)

**Comment by legalsylvain** [comment]
thanks !

**Pull request merged**
