### PR TITLE
8.0 Add support for bank.payment.lines

### PR DESCRIPTION
**Pull request by alexis-via**
The PR should be merged only when the following PR is merged: https://github.com/OCA/bank-payment/pull/214

### CODE REVIEW

**Comment by MOSAMAD** [comment]
:+1:

**Comment by brother-bernard** [comment]
:+1:

**Comment by gurneyalex** [comment]
travis build of 8.0 was recently greenified. can you rebase?

**Comment by alexis-via** [comment]
The bank.statement.lines PR has now been merged in OCA/bank-payment, so I merge this one.

**Pull request merged**
