### PR TITLE
[15.0] Add l10n_fr_department_partner_address

### PR DESCRIPTION
**Pull request by yankinmax**
This module adds French Departments (Départements) to partner address.

### CODE REVIEW

**Review by legalsylvain — CHANGES_REQUESTED** [review]
Hi. Thanks for sharing this contribution. General review : lgtm (code review / no test)

However, i see no reason to not integrate the view you introduce, directly in the main module l10n_fr_department as an improvment. Don't you think ?
It''ll make the code smaller and simpler.

**Comment by ivantodorovich** [comment]
> Hi. Thanks for sharing this contribution. General review : lgtm (code review / no test)
> 
> 
> 
> However, i see no reason to not integrate the view you introduce, directly in the main module l10n_fr_department as an improvment. Don't you think ?
> 
> It''ll make the code smaller and simpler.

Agree ☝️

**Comment by yankinmax** [comment]
@legalsylvain @ivantodorovich I agree with you, will open new PR

**Comment by yankinmax** [comment]
I close this PR as it has been superseded by https://github.com/OCA/l10n-france/pull/353

**Pull request closed without merging**
