### PR TITLE
12.0 mig l10n fr ecotaxe

### PR DESCRIPTION
**Pull request by mourad-ehm**
Migrate l10n_fr_ecotaxe to 12.0 and split it in 3 modules:
* l10n_fr_ecotaxe
* l10n_fr_ecotaxe_sale
* l10n_fr_ecotaxe_purchase
In this version we don't use account.tax in ecotaxe computation. Thus tax amount in no longer separated in accounting account.

### CODE REVIEW

**Comment by mourad-ehm** [comment]
ping @alexis-via , @sebastienbeau, @bealdav

**Review by MAG-Florian-Chevalier — APPROVED** [review]
Code seems ok (didn't check the .po files).
Tested on a local database, everything looks fine, ecotaxe is displayed on sale orders and invoices. Both weighted and fixed were tested.
Just some details I've seen and which might not be explained in the reame :
- Ecotaxe isn't added to the product price unit, I guess that it's included in it, so one might have to change the products price.
- Ecotaxe is not displayed in reports but I think it is intended

Regards,

**Comment by gurneyalex** [comment]
hello @mourad-ehm I'm interested in this module and migrating it to later Odoo versions. Could you rebase your PR and check the CI? I'll help getting it merged.

**Review by gurneyalex — APPROVED** [review]

**Comment by mourad-ehm** [comment]
Hi @MAG-Florian-Chevalier, Yes Ecotaxe is included in product price. 
For My client in V8 I made code modification to make ecotaxe not included in price : https://github.com/OCA/l10n-france/pull/279/commits/1c0afca476e2c084159427c4d88b72e0b39bd4fa#diff-4164807b798a2e6c83f7b0f21350bf8800d9f3fee8775126080288e5af914635R35 
I think that is good to add a some setting like Ecotaxe included in product price: Yes/no. 
In the same commit, I method _get_product_weight to allow get the weight depending on product variant (exemple tables variant with metal legs or wood legs). I will rebase this PR. Improvements can be made in an other PR.

**Comment by mourad-ehm** [comment]
Some one can explain why runbot is red ?

**Comment by ivantodorovich** [comment]
> Some one can explain why runbot is red ?

I believe it's just because of this:

```
2021-11-30 12:42:16,602 173 WARNING openerp_test odoo.models: The model account.ecotaxe.classification has no _description
2021-11-30 12:42:16,603 173 WARNING openerp_test odoo.models: The model account.ecotaxe.category has no _description
```

**Review by ajaniszewska-dev — APPROVED** [review]

**Pull request closed without merging**
