### PR TITLE
[9.0] Port l10n_fr_siret to v9

### PR DESCRIPTION
**Pull request by lbelorgey**

### CODE REVIEW

**Comment by alexis-via** [comment]
Please sign the CLA and tell us when it's done.
Thanks for this contribution :+1:

**Comment by lbelorgey** [comment]
Done. Waiting for confirmation.

**Comment by alexis-via** [comment]
@lbelorgey Could you resolve the conflicts, so that we can merge this ?

**Comment by lbelorgey** [comment]
Done. It's now clean. Thanks.

**Pull request merged**
