### PR TITLE
[14.0][ADD] l10n_fr_pos_cert_allow_change_qty

### PR DESCRIPTION
**Pull request by remi-filament**
l10n_fr_pos_cert adds a constraint on removing line in point of sale while selling products.
As far as I could tell, this is not required legally, and a real pain for cashier who cannot make mistake anymore when entering quantities otherwise it is shown on the ticket for customer...

This module bypasses this constraint

### CODE REVIEW

**Review by ivantodorovich — APPROVED** [review]

**Review by JulianaPoudou — APPROVED** [review]

**Review by hparfr — APPROVED** [review]

**Review by jordancoest — APPROVED** [review]

**Comment by legalsylvain** [comment]
@remi-filament : do you want to add you as maintainer of this module ? (Key in manifest)
Thanks

**Comment by remi-filament** [comment]
> @remi-filament : do you want to add you as maintainer of this module ? (Key in manifest) Thanks

I could but there is not much to maintain !
Let me know if you think I should ?

**Pull request merged**
