### PR TITLE
[16.0][MIG] Chorus Pro connector

### PR DESCRIPTION
**Pull request by alexis-via**
Factorize code between sale.order and invoice validation
Add timeout in requests
Forward-port improvements on payment mode check from v14 (https://github.com/OCA/l10n-france/pull/360/files)

### CODE REVIEW

**Comment by alexis-via** [comment]
Depends on https://github.com/OCA/edi/pull/706

**Review by legalsylvain — COMMENTED** [review]
/ocabot migration l10n_fr_account_invoice_facturx

**Comment by legalsylvain** [comment]
@alexis-via could you rebase and fix the conflict ?

**Pull request merged**
