### PR TITLE
[17.0] [REM] remove l10n_fr_ecotaxe

### PR DESCRIPTION
**Pull request by gurneyalex**
This should not have been merged, the modules are being generalized and moved to https://github.com/OCA/account-fiscal-rule

See #483

### CODE REVIEW

**Review by hparfr — APPROVED** [review]

**Comment by gurneyalex** [comment]
@sbidoul Is this ok or will it have nasty side effects on pypi / weblate / others ?

Similar question for #552 (same PR on 16.0)

**Comment by sbidoul** [comment]
@gurneyalex removing modules is fine. They will stay on PyPI though. If we want to discourage folks to install them, we have the option to yank the releases on PyPI.

**Comment by sbidoul** [comment]
Ping me when it's merged, I'll check weblate as I'm not sure it handles removals.

**Comment by gurneyalex** [comment]
@sbidoul both PRs merged

**Pull request merged**
