### PR TITLE
[14.0] cfonb: add support for XPF (decimals=0)

### LINKED ISSUE #120: Wrong amount imported from CFONB120 file -
Hi,

  When I try to import the line below from a CFONB120 file using account_bank_statement_import_fr_cfonb module, one number for the amount is missing:
0414889    00081XPF0 8261540101806161017  161017VIR A VISIOGREEN AGRICULTURE     00000000 0000000166587**J**032863054
  I get 166587 instead of 166587**1**.  According to our bank "J" stands for "1" in case of debit (see table below) as per the specifications attached.
[20130612113947_7_4_Releve_de_Compte_sur_support_informatique_2004_07.pdf](https://github.com/OCA/l10n-france/files/1436013/20130612113947_7_4_Releve_de_Compte_sur_support_informatique_2004_07.pdf)

Pour un montant créditeur “7B” et “41” à “49” pour + 0 à + 9 :
•	{ correspond à 0
•	A correspond à 1
•	B correspond à 2
•	C correspond à 3
•	D correspond à 4
•	E correspond à 5
•	F correspond à 6
•	G correspond à 7
•	H correspond à 8
•	I correspond à 9

Pour un montant débiteur “7D” et “4A” à “52” pour - 0 à – 9 :
•	} correspond à 0
•	J correspond à 1
•	K correspond à 2
•	R correspond à 3
•	M correspond à 4
•	N correspond à 5
•	correspond à 6
•	P correspond à 7
•	Q correspond à 8
•	R correspond à 9

  What can I do to fix this issue?

Best Regards,

### PR DESCRIPTION
**Pull request by alexis-via**
Should fix https://github.com/OCA/l10n-france/issues/120
@pierromanu If you have the opportunity to test with a real XPF CFONB file, it would be cool.

### CODE REVIEW

**Comment by alexis-via** [comment]
@cvinh are you available to have a look at this? I think it's interesting for you too !

**Comment by cvinh** [comment]
> @cvinh are you available to have a look at this? I think it's interesting for you too !

Thank you ! in PF we are still with EBICS buy it can evolve

**Comment by alexis-via** [comment]
@cvinh I don't understand your message. EBICS uses CFONB files for bank statements, right? So, if you use EBICS, you need this PR, right?

**Pull request merged**
