### PR TITLE
[15.0][MIG] l10n_fr_state

### PR DESCRIPTION
**Pull request by alexis-via**

### CODE REVIEW

**Review by legalsylvain — APPROVED** [review]
Thanks !

@sbidoul do you know why runboat is red one this one ?
Log says : no log found

**Review by ivantodorovich — APPROVED** [review]

**Comment by rvalyi** [comment]
> Thanks !
> 
> @sbidoul do you know why runboat is red one this one ? Log says : no log found

Runboat had a quota issue these last days. It was fixed. I restarted it so hopefully it becomes green.

**Comment by sbidoul** [comment]
I clicked `reset` and runboat is green, now.

**Pull request merged**
