### PR TITLE
[17.0] dotfiles update needs manual intervention

### PR DESCRIPTION
**Pull request by sbidoul**
Dear maintainer,

After updating the dotfiles, `pre-commit run -a`
fails in a manner that cannot be resolved automatically.

Can you please have a look, fix and merge?

Thanks,

### CODE REVIEW

**Comment by legalsylvain** [comment]
Hi @sbidoul. 

I don't understand why the errors was not present before ? 

```
 account_banking_fr_lcr/models/account_payment_order.py:119:89: E501 Line too long (107 > 88)
l10n_fr_chorus_account/models/account_move.py:86:89: E501 Line too long (121 > 88)
```

rule about line length is not new at all ? 

Anyway : @alexis-via : could you fix your modules ?
thanks.

**Comment by pedrobaeza** [comment]
The line length rule was forgotten on the initial new ruff linter template, that was used to initialize 17.0 branches, but when it was later added, repos were not updated with it, so the problem grew.

**Comment by dreispt** [comment]
Done!

**Review by legalsylvain — COMMENTED** [review]
Thanks @dreispt ! 

/ocabot merge patch

**Comment by dreispt** [comment]
Made a tentative fix.

**Pull request merged**
