### PR TITLE
Replace \r \n \t in export to avoid file interpretation errors + add encoding option

### PR DESCRIPTION
**Pull request by mourad-ehm**
For the real case of use several account move lines are imported from external source. 
This import can contain some special characters which generate a fec file with interpretation errors.

### CODE REVIEW

**Comment by mourad-ehm** [comment]
ping @alexis-via , @bealdav

**Review by bealdav — APPROVED** [review]

**Comment by alexis-via** [comment]
I'll take advantage of this PR to add other improvements such as add an option for encoding... I'm currently working on it.

**Comment by alexis-via** [comment]
Some of the points addressed in this PR are related to the bug https://github.com/odoo/odoo/issues/15781 and https://github.com/OCA/l10n-france/issues/99

**Comment by alexis-via** [comment]
I generated a FEC with this PR on a real big production DB on odoo v8 and checked the result with the latest version of https://www.economie.gouv.fr/dgfip/outil-test-des-fichiers-des-ecritures-comptables-fec and everything was OK.

**Review by alexis-via — APPROVED** [review]

**Comment by mourad-ehm** [comment]
ping @sebastienbeau , could you merge this PR please ?

**Pull request merged**
