### PR TITLE
[REF][14.0] Fix CI pre-commit + travis.yml, ignoring modules

### PR DESCRIPTION
**Pull request by legalsylvain**
ignoring the following modules thats makes travis / runbot red on 12.0 branch 

- l10n_fr_account_invoice_import_facturx
- l10n_fr_business_document_import
- l10n_fr_intrastat_product
- l10n_fr_intrastat_service
- account_balance_ebp_csv_export
- account_banking_fr_lcr
- account_statement_import_fr_cfonb
- l10n_fr_account_tax_unece
- l10n_fr_fec_oca
- l10n_fr_mis_reports

### CODE REVIEW

**Comment by ivantodorovich** [comment]
Hehe, getting there :sweat_smile: 
I feel we're excluding the whole repo :/

**Comment by legalsylvain** [comment]
hehe ! I I promise myself to make this branch green again ;-)

**Comment by ivantodorovich** [comment]
image

**Review by rvalyi — APPROVED** [review]
Great. I was suggesting the same change to @alexis-via a few days ago... We also use the same method to avoid running Black on generated code or Prettier on test XML in OCA/l10n-brazil.

**Review by ivantodorovich — APPROVED** [review]
LG (after squashing ofc) :tada: thanks a lot !

**Comment by alexis-via** [comment]
Thanks for the Donald Trump quote. This is really a Donald Trump quality-level PR: problems are not solved, they are just hidden under the carpet. No real work. Excluding l10n_fr_fec_oca can make sense because this module generates a lot of warnings which are not easy to solve, but excluding all the other modules is stupid because the other problems were easy to solve by someone with experience of travis/pre-commit config. For example, on l10n_fr_intrastat_service, only the file des.xsd, which is the official file from the French administration, should be excluded from pre-commit/isort ; no need to exclude the whole module and set it as Alpha module !!! l10n_fr_intrastat_service exists since Odoo v5.0, cf https://bazaar.launchpad.net/~new-report-intrastat-team/new-report-intrastat/5.0/files/head:/l10n_fr_intrastat_service and a lot of companies use it in production... and now it's readme says "This is an alpha version, the data model and design can change at any time without warning. Only for development or testing purpose, do not use in production."

This PR was merged super-fast in less than 24 hours. So I hope to get the real/serious PR that really solves the problem really fast too, removing the Alpha status and solving the easy pre-commit/travis errors (again, I'm OK to exclude l10n_fr_fec_oca from the tests for the moment).

**Comment by alexis-via** [comment]
@legalsylvain Could you have your answer on my comment above ? When do you plan to do the real/serious PR ?

**Comment by legalsylvain** [comment]
Hi @alexis-via. 

> Could you have your answer on my comment above ?

I'm on holidays for the time being. That's why I didn't answered.

>  When do you plan to do the real/serious PR ?

I didn't plan to make other PRs. Excluded modules are modules I didn't developed, I don't use, I don't maintain, I don't know. All of the PRs has been merged without respecting the OCA conventions (ocabot).
CI was totally red, it is now half green (8 modules / 18 modules), which is better as @rvalyi @ivantodorovich pointed out.
But as said before [here](https://github.com/OCA/l10n-france/issues/299#issue-966240913), I can help you to fix your modules and to understand better the OCA CI system, as you said [here](https://github.com/OCA/l10n-france/issues/299#issuecomment-899072334) that you was very confortable with that topic.

If you're OK with that and especially to stop merging without ocabot, I can call you the next weeks to see how to move forward on this topic. Let me know.

kind regards.

**Comment by alexis-via** [comment]
@legalsylvain I'm very disappointed by your attitude. Saying that you don't plan to fix CI issues because "I didn't develop, I don't use, I don't maintain, I don't know"is certainly not the attitude I expect from someone with commit rights on OCA/l10n-france. In other situations (including here on OCA/l10n-france), you happen to contribute to modules on which you're not the initial author and that's what the OCA is all about, doing team work on OCA modules. In the case of simple CI issues (i.e. most CI issues except those on the module l10n_fr_fec_oca), it would have taken you the same time fixing the issues itself than excluding the modules from the tests and flagging them as Alpha. Flagging those modules as Alpha in the middle of August in less than 24h is extremely disrespectful for the authors/contributors of those modules.

You say I didn't respect the rules on CI, but you didn't respect the OCA rules either because this PR was merged less than 24h after it's creation.
So I understand that I'll have to create the real/serious PR myself, as you don't plan to do it. OK, I'll do the real/serious work. And I'll also take this occasion to update the list of people with commit rights on OCA/l10n-france and you'll not be part of them.

**Comment by ivantodorovich** [comment]
Hello, I'm thankful for @legalsylvain work on restoring the CI. Before his work, we couldn't even test any new contributions on this project. Not only these modules' tests were broken, the whole CI was broken. 
Now, only these modules' tests are skipped, but we can test other modules. The situation is still far from ideal, I agree, all modules should pass the CI.. but at least it's better than before.

I sense the reason you're not happy with this is because of the change in the module's maturity level to "Alpha". To be fair, all modules merged in the OCA must pass the CI, we don't have any maturity level defined for modules not passing the CI. Even Alpha modules must pass the CI. [You can read more about them here](https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/oca_module_lifecycle_development_status.rst). Anyway, my guess is he picked the lowest possible level to keep track of these modules until they're finally tested again. Having said that, if it's such big of an issue, I suggest we simply remove the "Alpha" status from these modules' manifest, and track them through Github Issues until the real fix is done.

As for the real fix, having these modules actually pass the CI.. we can't ask @legalsylvain to do that. Most of us work on customer's budgets, so my suggestion is: next time one of these modules is required by any of our customers, get some budget to fix their tests and do it.

Btw merging the PR in less than 24hs is not breaking any rules AFAIK. Many PRs are merged quickly in several OCA repositories. [Here's a reminder of merging rules](https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#please-respect-a-few-basic-rules). If the 24hs thing is really a rule I suggest we update that document because it's otherwise misleading. On the other hand, the reason we're even having this conversation is because of other PRs were merged without reviews, broken ci and skipping ocabot. :(

**Comment by pedrobaeza** [comment]
Yes, please don't fight between 2 very active OCA contributors like you, Alexis and Sylvain.

**Pull request merged**
