### PR TITLE
[12.0] [ADD] l10n_fr_cedex module

### PR DESCRIPTION
**Pull request by remi-filament**
Cedex field added on res_partner

### CODE REVIEW

**Review by flotho — APPROVED** [review]
LGTM

**Review by legalsylvain — CHANGES_REQUESTED** [review]
Thanks for this module @remi-filament.

1) Testing on runbot, to check if cedex field is displayed on report, it is generating a bug.
Step to reproduce : 
- set cedex on a partner
- try to print a quotation for this partner. (for instance, purchase.order).

Server error : 

```
  File "/.repo_requirements/odoo/odoo/addons/base/models/res_partner.py", line 695, in _get_name
    name = name + "\n" + partner._display_address(without_company=True)
  File "/.repo_requirements/odoo/odoo/addons/base/models/res_partner.py", line 936, in _display_address
    return address_format % args
KeyError: 'cedex'

Error to render compiling AST
KeyError: 'cedex'
Template: purchase.report_purchasequotation_document
Path: /templates/t/t/t[4]/t/div/div
Node: <div t-field="o.picking_type_id.warehouse_id.partner_id" t-options="{&quot;widget&quot;: &quot;contact&quot;, &quot;fields&quot;: [&quot;address&quot;, &quot;phone&quot;], &quot;no_marker&quot;: True, &quot;phone_icons&quot;: True}"/>
              
```

2) I also think that the field should be available on ``res.company`` form that inherit from ``res.partner``.

**Comment by remi-filament** [comment]
Thanks for the review @legalsylvain, you are right, I forgot half of the module...
I added cedex field to _address_fields() for proper render.
I realized that the \n from csv file were not taken correctly into account, so I replaced it by hooks for updating database directly.
If you could check again, it should be working now !

**Comment by remi-filament** [comment]
And porting on res_company as requested

**Review by legalsylvain — COMMENTED** [review]
Hi @remi-filament 

Much better ! 

Tested on runbot.
- set cedex on res.company : OK
- display cedex on report for res.company : OK

- display cedex for res.partner : KO. (or maybe I missed something.)

See below, i set CEDEX on the current company, and the current customer. 

image

question : don't we have to add a constraint on the new field ? 
cedex field should be formated like the following string :  

CEDEX XX 
where XX is a number. 

don't you think ? 

ref : https://fr.wikipedia.org/wiki/Courrier_d%27entreprise_%C3%A0_distribution_exceptionnelle

**Comment by remi-filament** [comment]
@legalsylvain To display partner cedex on report, country needs to be France, any DOM-TOM, Andorra, or Monaco. Otherwise it makes no sense from my point of view.

Regarding the constraint, I am not sure, since sometimes you can have only CEDEX, sometimes CEDEX X, sometimes CEDEX XX... We could force to have the field starting with CEDEX but I am not sure whether mandatory ?

**Pull request closed without merging**
