### PR TITLE
[12.0][FIX] Department code from 1 (->01) to 9 (->09)

### PR DESCRIPTION
**Pull request by alexis-via**
Without this fix, department_id was False on partners in these departments

### CODE REVIEW

**Review by ivantodorovich — APPROVED** [review]

**Review by legalsylvain — APPROVED** [review]

**Comment by legalsylvain** [comment]
Please check travis

**Comment by alexis-via** [comment]
Strictly speaking, we should add a migration script to fix data on res.partner field department_id.

**Comment by alexis-via** [comment]
I'll do it when I have time

**Comment by alexis-via** [comment]
Here is the migration script. I tested it on my laptop ; the department_id of the partner was fixed. Ready to merge for me now.

**Review by ivantodorovich — APPROVED** [review]

**Comment by legalsylvain** [comment]
Thanks for the migration script.

/ocabot merge patch

**Comment by legalsylvain** [comment]
@alexis-via, could you fix upstream ? The last merge broke travis.

https://travis-ci.org/github/OCA/l10n-france/branches

Thanks !

**Comment by legalsylvain** [comment]
oui, c'est une façon de "régler" le problème ;-)

**Pull request merged**
