### PR TITLE
[12.0] [Add] unicodecsv dependency

### PR DESCRIPTION
**Pull request by sama62**
need it for FEC.

### CODE REVIEW

**Comment by sama62** [comment]
ping @flotho @alexis-via @legalsylvain

**Review by legalsylvain — COMMENTED** [review]
Hi @sama62. 

Makes sense. 

However, the installation of this library is currently done in the ``.travis.yml``.
https://github.com/OCA/l10n-france/blob/12.0/.travis.yml#L30
(otherwise, CI would be red)
you should remove the unicodecsv here.


Maybe we could add the 5 lib in the requirement.txt file :  ``unicodecsv unidecode ofxparse PyPDF2 factur-x``
and remove the whole line in the ``.travis.yml`` file.

What is your PoV @alexis-via. Is there any reason to make the installation in the ``.travis.yml`` file and not in the ``requirements.txt`` file ?

kind regards.

**Comment by flotho** [comment]
Hi @legalsylvain @alexis-via , 
I think that requirements is the most "common" way to declare dependencies so I agree on this : 
Maybe we could add the 5 lib in the require

> ment.txt file : unicodecsv unidecode ofxparse PyPDF2 factur-x
> and remove the whole line in the .travis.yml file.

Moreover it's the case on versions > 12.0

**Comment by alexis-via** [comment]
Yes, go ahead, move it from travis.cfg to requirements.txt

**Comment by flotho** [comment]
@sama62 , you have all the directives form the maintainers, let's go !

**Comment by sama62** [comment]
Thank you!

**Review by legalsylvain — APPROVED** [review]

**Review by flotho — APPROVED** [review]

**Comment by flotho** [comment]
congrats @sama62 for your first contribution !

**Comment by sama62** [comment]
> congrats @sama62 for your first contribution !

Merci @flotho

**Pull request merged**
