### PR TITLE
Update pre-commit conf

### PR DESCRIPTION
**Pull request by yankinmax**

### CODE REVIEW

**Comment by yankinmax** [comment]
@alexis-via @pedrobaeza

**Review by pedrobaeza — APPROVED** [review]
Merging as administrative transaction

**Comment by legalsylvain** [comment]
Hi @yankinmax.

You replace "l10n-france" reference by "crm" reference in that PR. So https://github.com/OCA/l10n-france/pull/393 is failing.
I'll fix that.
In the meatime, @yankinmax could you take a look if you made the same mistake (copy / paste) in other PR ? 

thanks !

**Comment by yankinmax** [comment]
@legalsylvain I see, my bad, sorry for that. I've checked this is only the case.

**Pull request merged**
