### PR TITLE
[16.0][MIG] l10n_fr_fec_oca

### PR DESCRIPTION
**Pull request by alexis-via**

### CODE REVIEW

**Comment by alexis-via** [comment]
I included the ir.rule suggested on https://github.com/odoo/odoo/pull/115958

**Comment by alexis-via** [comment]
Green tests require https://github.com/OCA/server-ux/pull/667

**Comment by alexis-via** [comment]
@fmdl In the end, I changed your ir.rule: I added company_id on the wizard and I wrote the classical ir.rule domain [('company_id', 'in', company_ids)]

**Review by houzefa-abba — APPROVED** [review]

**Pull request merged**
