### PR TITLE
[ADD] l10n_fr_certification_pos_offline

### PR DESCRIPTION
**Pull request by legalsylvain**
This module extend Point of Sale module regarding french certification.

It will print the hash on the bill, or print a warning / prevent the print if the point of sale is offline.

See the readme file for a complete description.
https://github.com/grap/l10n-france/blob/10.0_l10n_fr_certification_pos_offline/l10n_fr_certification_pos_offline/README.rst

This module is inspired from the big PR on V8.0 that was backporting certification process from Odoo V9.0.

https://github.com/OCA/l10n-france/pull/108

### CODE REVIEW

**Comment by gaelTorrecillas** [comment]
Hello,

I tested the PR, 
- If I am disconnected, the three modes work (warning pop up or warning on the ticket).
- If we have a mode no printing,  after the warning pop up I have the page "ticket preview" (even if I pass it automatically).
  - The print button throws an error. So I can not print the ticket after reconnection with this button.

certif_pos_error


- Sometimes when the POS has several modules, we can not send the report in time. 
- An option to refocus the timeout it was not interesting to set up for this module?

**Comment by legalsylvain** [comment]
Hi @gaelTorrecillas, 
Thanks for your review ! 

> The print button throws an error. So I can not print the ticket after reconnection with this button.

OK. I have to hide the button in that case. (It is not possible in that case to print the bill, because in the core of point of sale, the bill is generated at the first try (of send the pos.order)).

> Sometimes when the POS has several modules, we can not send the report in time.

I never had this problem. could you mention wich modules you are using ?

> An option to refocus the timeout it was not interesting to set up for this module?

Not sure to understand. Are you talking about the timeout to send the pos.order to the backoffice via the function create_from_ui ?

Thanks for the clarification.

**Comment by gaelTorrecillas** [comment]
Hi @legalsylvain,

I do not know which modules add time when sending the pos.order to the backend.

With a demo base and the minimals modules to test your PR, I don't have problem. 
The pos order is sent and I can quickly print the ticket. But as soon as there are some modules that impact the sending, sometimes we have to click on the icon at the top right because the first shipment failed. Hence an option to adjust this timeout.

it's not possible to generate the receipt when we send the pos order? For exemple if the sending failled, the seller must be able to print the receipt once the pos order sent, right?

**Comment by flotho** [comment]
Hi @legalsylvain , we are suspecting perfs issues when working in multi workers.
Could you provide us your conf for your tests?

regards

**Comment by legalsylvain** [comment]
In my config workers = 0. but I doubt that this module makes back office slower, because the only thing I add is a simple read on a pos.order model.

Regarding @gaelTorrecillas remarks about timeout, I developped a small module to alter the timeout of the PoS. could you install it and review it ? https://github.com/OCA/pos/pull/239. 
FYI, timeout is set to 7,5 second by default, which is rather long.

Thanks for your feedback.

regards.

**Comment by gaelTorrecillas** [comment]
hello,

we found the configuration which add the waiting time before the printing.

If we put a value in l10n_en_prevent_print_legacy, we observe the problem.

below,we have the server logs with the customer data.

```
2018-01-22 11:38:52,101 19615 DEBUG test odoo.api: call pos.order().create_from_ui([{u'to_invoice': False, u'data': {u'canceled_lines': [], u'user_id': 17, u'name': u'Order 06766-017-0039', u'promo_categories': [], u'partner_id': False, u'amount_paid': 24.900000000000002, u'pos_session_id': 6766, u'lines': [[0, 0, {u'product_is_promo': False, u'discount_product': False, u'product_id': 195, u'max_quantity': 1, u'promo': False, u'price_unit': 24.9, u'promo_product_id': False, u'pricelist_items_ids': [], u'qty': 1, u'pack_lot_ids': [], u'discount': 0, u'min_quantity': False, u'quantity_included': False, u'id': 933, u'base_product_id': False, u'tax_ids': [[6, False, [61]]]}]], u'statement_ids': [[0, 0, {u'journal_id': 18, u'amount': 24.900000000000002, u'name': u'2018-01-22 11:38:14', u'account_id': 1314, u'statement_id': 34007}]], u'creation_date': u'2018-01-22 11:38:14', u'amount_tax': 2.2600000000000002, u'fiscal_position_id': False, u'uid': u'06766-017-0039', u'old_base_categories': {}, u'promo_orderlines_obj': [], u'amount_return': 0, u'sequence_number': 39, u'amount_total': 24.900000000000002}, u'id': u'06766-017-0039'}, {u'to_invoice': False, u'data': {u'canceled_lines': [], u'user_id': 17, u'name': u'Order 06766-017-0040', u'promo_categories': [], u'partner_id': False, u'amount_paid': 10, u'pos_session_id': 6766, u'lines': [[0, 0, {u'product_is_promo': False, u'discount_product': False, u'product_id': 598, u'max_quantity': 1, u'promo': False, u'price_unit': 10, u'promo_product_id': False, u'pricelist_items_ids': [], u'qty': 1, u'pack_lot_ids': [], u'discount': 0, u'min_quantity': False, u'quantity_included': False, u'id': 1035, u'base_product_id': False, u'tax_ids': [[6, False, [61]]]}]], u'statement_ids': [[0, 0, {u'journal_id': 18, u'amount': 10, u'name': u'2018-01-22 11:38:52', u'account_id': 1314, u'statement_id': 34007}]], u'creation_date': u'2018-01-22 11:38:52', u'amount_tax': 0.91, u'fiscal_position_id': False, u'uid': u'06766-017-0040', u'old_base_categories': {}, u'promo_orderlines_obj': [], u'amount_return': 0, u'sequence_number': 40, u'amount_total': 10}, u'id': u'06766-017-0040'}])
2018-01-22 11:38:52,615 19615 WARNING test odoo.models: pos.order.line.create() includes unknown fields: base_product_id, discount_product, max_quantity, min_quantity, promo, promo_product_id, quantity_included
 2018-01-22 11:38:55,630 19615 INFO test werkzeug: 127.0.0.1 - - [22/Jan/2018 11:38:55] "POST /longpolling/poll HTTP/1.1" 200 -
2018-01-22 11:39:00,086 19615 DEBUG ? odoo.service.server: cron0 polling for jobs
2018-01-22 11:39:02,081 19615 INFO test werkzeug: 127.0.0.1 - - [22/Jan/2018 11:39:02] "POST /web/dataset/call_kw/pos.order/create_from_ui HTTP/1.1" 200 -
2018-01-22 11:39:02,118 19615 DEBUG test odoo.api: call pos.order(193433,).get_certification_information()
2018-01-22 11:39:02,131 19615 INFO test werkzeug: 127.0.0.1 - - [22/Jan/2018 11:39:02] "POST /web/dataset/call_kw/pos.order/get_certification_information HTTP/1.1" 200 -
```
My test on the odoo test base also has a slightly longer wait time than when I leave the field empty.

the waiting time seems to be proportional to a factor like the database or any other data.

edit : I wrong, this result is obtained because we have this module. But The recording time (= waiting time) isn't impacted by it.

**Comment by flotho** [comment]
Hi @legalsylvain , what's your point of view on this one : https://github.com/odoo/odoo/issues/22638 ?

**Comment by flotho** [comment]
Hi @legalsylvain , what is the process for merging your PR? Have we got the availability to approve your PR?
Regards

**Comment by gurneyalex** [comment]
@flotho  you can certainly review and approve the PR if you think it works fine. There are some issues pointed in the comments with no further commits from Sylvain which makes it hard for ppl not using the POS to merge.

**Review by flotho — APPROVED** [review]

**Comment by legalsylvain** [comment]
Hi all,

- For me timeout problem can be solved with the now merged module ```pos_timeout```. https://github.com/OCA/pos/pull/239. But yes, As the current module makes the PoS working in a quite "online mode", The process will take times if the pos order takes time to be proceeded (including picking / move creation). That is the design of this module.
- about the log provided by @gaelTorrecillas, warning errors seems to come from other custom modules. 
WARNING test odoo.models: pos.order.line.create() includes unknown fields: **base_product_id, discount_product, max_quantity, min_quantity, promo, promo_product_id, quantity_included**

So @gurneyalex, I don't know exactly what I have to fix, but for me, this module is ready to review. (and merge).

@alexis-via : could you take a look on that module ?

Regards.

**Comment by legalsylvain** [comment]
ping : @l10n-france team. @alexis-via.
regards.

**Comment by gaelTorrecillas** [comment]
Hello @legalsylvain,

After ours tests,
We have a few seconds to print the receipt.
- 10 seconds between our click and printing.
This is a problem because our test is done at a point of sale and, in general, odoo receives a lot of post orders and has to send the responses to print the receipts.
Sometimes we have a time out.

**Comment by flotho** [comment]
Hi @legalsylvain ,

@gaelTorrecillas and I made additional tests  and we could say that your code works well. @gaelTorrecillas will review your code a,nd approve it.

Yet there is a major problem related to the way the Odoo POS is waiting for the answer of the server. In the following method https://github.com/odoo/odoo/blob/10.0/addons/point_of_sale/models/pos_order.py#L535 the picking part is really long regarding all the rest of the process.
For example, in our tests it tooks less than 2s for getting an answer for pure services products but more that 7 second for fullfilling all the process with products. This part is really a problem for us and our customer. 

My proposal for OCA is to work with https://github.com/OCA/queue and delay the part that are coming between https://github.com/odoo/odoo/blob/10.0/addons/point_of_sale/models/pos_order.py#L618 and the end of the method. This way I also wondering if there is any way possible to improve the way Odoo is creating the orders.
So regarding the @MindAndGo team all your work is done and it's a great job you offered to the community. Thanks for this!

**Review by gaelTorrecillas — APPROVED** [review]

**Comment by flotho** [comment]
Hi @gurneyalex ,

We have 2 reviewers on this PR, is there anymore requirements for a merge?
Thanks for sharing your recommendations.
regards

**Comment by flotho** [comment]
Hi @pedrobaeza , sorry for the ping,
who is the maintainer of this repo? 
Is everything Ok for merging?
regards

**Comment by legalsylvain** [comment]
~Hi. I'm the maintainer of this repo. ;-)~ I'm currently on Hollidays, and go back the next week. In the meantime, I think we should suspend this PR, and wait if Odoo/#26314 is merged. It will maybe change things and we should check the compatibility.

regards.

(Note : sorry I'm not the main maintainer of this repo, I was confonding with OCA/pos because this PR is a l10n + pos module. @alexis-via was one of the maintainer)

**Pull request closed without merging**
