### PR TITLE
16.0 mig l10n fr ecotaxe product

### PR DESCRIPTION
**Pull request by mourad-ehm**
depends https://github.com/OCA/l10n-france/pull/448

### CODE REVIEW

**Comment by bealdav** [comment]
Please @mourad-ehm could you use these intsructions to make runboat up ?
https://github.com/OCA/maintainer-tools/wiki/Use-temporary-reference%28s%29-to-another-pull-request%28s%29

**Comment by legalsylvain** [comment]
/ocabot migration [l10n_fr_ecotaxe_product](https://github.com/OCA/l10n-france/pull/450/files#diff-85b092f7018e58597645462dfe1ea38b2f87bcddf51e9e248901c5f9f9232d15)

**Comment by pfranck** [comment]
I face an issue with the test on the product, we need to activate the multi-variant option for the test

**Comment by mourad-ehm** [comment]
@pfranck, The goal of this module is to manage ecotaxe on product variants. If you have no variant don't use this module

**Comment by bealdav** [comment]
Finally it seems this module is no more required.

PR can be closed

**Comment by mourad-ehm** [comment]
> Finally it seems this module is no more required.
> 
> PR can be closed

Yes, mange of product variants was integrated in the  l10n_fr_ecotaxe module

**Pull request closed without merging**
