### PR TITLE
[12.0] - migration  l10n_fr_naf_ape

### PR DESCRIPTION
**Pull request by sbejaoui**

### CODE REVIEW

**Review by alexis-via — APPROVED** [review]

**Review by legalsylvain — CHANGES_REQUESTED** [review]
could you fix travis ? you make a reference to a module that does'nt belong to l10n-france.

raise UserError(_("You try to install module '%s' that depends on module '%s'.\nBut the latter module is not available in your system.") % (module.name, dep.name,))
odoo.exceptions.UserError: ("You try to install module 'l10n_fr_naf_ape' that depends on module 'l10n_eu_nace'.\nBut the latter module is not available in your system.", '')

(ref : Travis)

regard.

**Comment by alexis-via** [comment]
Depends on this PR https://github.com/OCA/community-data-files/pull/53

**Review by remi-filament — APPROVED** [review]

**Comment by remi-filament** [comment]
@legalsylvain Travis is failing because it cannot find the l10n_eu_nace, since corresponding [OCA/community-data-files#53](https://github.com/OCA/community-data-files/pull/53) is not yet merged...
I do not think there is anything we can do on this module until it is merged.

**Comment by sbejaoui** [comment]
Hi,

As the work done in [community-data-files\#53](https://github.com/OCA/community-data-files/pull/53) by adding dedicated model for nace codes. A new field `nace_id` was added to the `res.partner` model.

IMO, there is no need to have the `ape_id` field. I made a migration script to fill the new field.
The NACE label should be translated to APE after we merge this.

Regards,

**Comment by sbejaoui** [comment]
Hi @legalsylvain ,

Can you update you review to be able to merge this PR once https://github.com/OCA/community-data-files/pull/53 is merged

Thanks.

**Comment by legalsylvain** [comment]
hi @sbejaoui. As https://github.com/OCA/community-data-files/pull/53 is merged, could you update the ``oca_dependency`` files to avoid to use an obsolete branch ? 

Once done, could be merge.

kind regards.

**Pull request closed without merging**
