### PR TITLE
[14.0] DAS2 update for millesime 2024 using the new pyfrdas2 lib

### PR DESCRIPTION
**Pull request by alexis-via**
Replaces https://github.com/OCA/l10n-france/pull/517

### CODE REVIEW

**Comment by alexis-via** [comment]
pre commit error is unrelated... grrr !

**Comment by legalsylvain** [comment]
This PR should fix pre-commit stuff : https://github.com/OCA/l10n-france/pull/531

Note : your tests are also red because the installation of pyfrdas2 failed. Could you take a look ? 
Thanks.

**Comment by alexis-via** [comment]
Fixed ! The problem was in my lib pyfrdas2, which declared the min python version to 3.8. I changed it to 3.6 because the tests of v14 use python 3.6, and now it works well.

**Pull request merged**
