### PR TITLE
FIX travis in l10n-france

### PR DESCRIPTION
**Pull request by bealdav**

### CODE REVIEW

**Comment by bealdav** [comment]
There are a lot pylint alerts because a misconfigured travis.yml since a long time.
https://travis-ci.org/OCA/l10n-france/jobs/650060596#L351-L370

cc @alexis-via 

I think we can merge this PR as it and fix misc pylint error after

What do you think @sbidoul ? It's the same fix than in intrastat.

**Comment by bealdav** [comment]
Because of failed I think it must be merged exceptionally with github button, thanks

**Comment by sbidoul** [comment]
I've not looked closely but I'd say it's read because the main branch is red and it will remain red after a manual merge.

**Comment by bealdav** [comment]
Yes you're right but then it's the problem of modules maintainer not of the repo maintainer, even if there are often the same people

**Review by legalsylvain — APPROVED** [review]

**Comment by bealdav** [comment]
@sbidoul now fixed, thanks

**Comment by bealdav** [comment]
Please @legalsylvain as PSC here could you merge please ? Thanks

**Comment by legalsylvain** [comment]
No problem, but I'd like to have a little & quick :+1: from @alexis-via for changes introduced in the modules he developped specially this file https://github.com/OCA/l10n-france/pull/209/files#diff-ae58828698fffa250c5aba6c59b78d43

Do you think it's possible ? 

kind regards.

**Comment by bealdav** [comment]
Theoretically, yes but @alexis-via  doesn't answer even when joined by misc channels including mails. I think he doesn't like review. But we have to go ahead. I imagine that @alexis-via measure risk and assume to not answer fix on its modules. Thanks for your consideration for his code. I let you judge of what to do

**Comment by legalsylvain** [comment]
OK. Let's go ahead.

**Comment by bealdav** [comment]
Ahhhh

npm ERR! code E403
npm ERR! 403 Forbidden: eslint@latest
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2020-02-17T11_11_41_340Z-debug.log
The command "travis_install_nightly" failed and exited with 1 during .

**Comment by bealdav** [comment]
> After fixing the problem, you can re-issue a merge command. Please refrain from merging manually as it will most probably make the target branch red.

In that case it couldn't be worst

**Comment by sebastienbeau** [comment]
let's retry /ocabot merge

**Pull request merged**
