### PR TITLE
[14.0] intrastat: adapt to changes in OCA/intrastat-extrastat

### PR DESCRIPTION
**Pull request by alexis-via**
Adapt to breaking changes introduced by https://github.com/OCA/intrastat-extrastat/pull/149

### CODE REVIEW

**Comment by ivantodorovich** [comment]
Since the other PR hasn't been merged yet, you can add a commit like this: https://github.com/OCA/account-invoicing/pull/1060/commits/c630385b95de77309861ef289915cecf8aeb0623 for the CI to run

It has to be removed before merging, though.. so a warning on the PR description also helps 😅

**Comment by alexis-via** [comment]
I don't see what's the problem here. I re-ran travis and it is green. I'll try again.

**Comment by alexis-via** [comment]
The error seems completely unrelated. I guess I'll merge it manually, unless if someone is able to find the root cause of the pb.

**Pull request merged**
