### PR TITLE
8.0 hr expense private car

### PR DESCRIPTION
**Pull request by sebastienbeau**
Move PR from LP : https://code.launchpad.net/~akretion-team/openerp-french-localization/hr-expense-private-car-80/+merge/236784

### CODE REVIEW

**Comment by gurneyalex** [comment]
can you rebase?

**Comment by legalsylvain** [comment]
ping @sebastienbeau.

**Comment by pedrobaeza** [comment]
Is this going to be continued?

**Comment by alexis-via** [comment]
Rebased.

**Comment by alexis-via** [comment]
This PR requires this other PR for hr_expense_onchange: https://github.com/OCA/hr/pull/47 but it was never merged, although I think it was useful for hr_expense v8 users. But the focus of the work is now for hr_expense v10. I will either include this in a single "hr_expense_usability" module on https://github.com/akretion/odoo-usability (so out of the OCA), or continue to try the OCA way with several small modules. Given the experience on v8, I will probably choose the first option.

**Comment by alexis-via** [comment]
I confirm I choose the first option: support for private car expenses is now part of hr_expense_usability: https://github.com/akretion/odoo-usability/tree/10.0/hr_expense_usability

**Pull request closed without merging**
