### PR TITLE
12.0 Apply copier

### PR DESCRIPTION
**Pull request by legalsylvain**

### CODE REVIEW

**Comment by legalsylvain** [comment]
I don't understand why the CI fails.
The error is : ``Field 'domain' used in attributes must be present in view but is missing:``
when installing dependency. (agreement_account module)

````
2022-11-24 09:04:19,914 243 INFO odoo odoo.modules.loading: loading agreement_account/views/agreement.xml 
2022-11-24 09:04:19,979 243 INFO odoo odoo.addons.base.models.ir_ui_view: Field 'domain' used in attributes must be present in view but is missing:
 - 'domain' in attrs="{'invisible': [('domain', '!=', 'purchase')]}"
 - 'domain' in attrs="{'invisible': [('domain', '!=', 'sale')]}"

Error context:
View `invoice.button.agreement.form`
[view_id: 863, xml_id: n/a, model: agreement, parent_id: 339] 
2022-11-24 09:04:19,984 243 WARNING odoo odoo.modules.loading: Transient module states were reset 
2022-11-24 09:04:19,985 243 ERROR odoo odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "/opt/odoo/odoo/models.py", line 1128, in _validate_fields
    check(self)
  File "/opt/odoo/odoo/addons/base/models/ir_ui_view.py", line 351, in _check_xml
    self.postprocess_and_fields(view.model, view_doc, view.id)
  File "/opt/odoo/odoo/addons/base/models/ir_ui_view.py", line 1151, in postprocess_and_fields
    self.raise_view_error("\n".join(msg_lines), view_id)
  File "/opt/odoo/odoo/addons/base/models/ir_ui_view.py", line 568, in raise_view_error
    raise ValueError(message)
ValueError: Field 'domain' used in attributes must be present in view but is missing:
 - 'domain' in attrs="{'invisible': [('domain', '!=', 'purchase')]}"
 - 'domain' in attrs="{'invisible': [('domain', '!=', 'sale')]}"

````

**Review by alexis-via — CHANGES_REQUESTED** [review]
You cannot change the licence of l10n_fr_fec_oca without prior approval of Odoo SA, because l10n_fr_fec_oca is a fork of l10n_fr_fec

**Comment by legalsylvain** [comment]
closing. superseded by https://github.com/OCA/l10n-france/pull/446

**Pull request closed without merging**
