### PR TITLE
8.0 New FR regions starting 2016-01-01

### PR DESCRIPTION
**Pull request by alexis-via**

### CODE REVIEW

**Comment by alexis-via** [comment]
Migrations scripts are ready now.

**Comment by alexis-via** [comment]
One thing left: align the state codes with the names used by geonames. At the moment, if you use base_location_geonames_import (OCA/partner_contact) together with l10n_fr_state, you get double entries for French regions because they don't use the same codes for states. This pb is not linked to this PR ; it has unfortunately always been like that, but I figured it out just now...

**Comment by alexis-via** [comment]
And for the moment, geonames.org hasn't been updated with the new regions.

**Comment by gurneyalex** [comment]
:+1:

**Comment by brother-bernard** [comment]
:+1: using this code in production

**Comment by alexis-via** [comment]
Geonames is still not up-to-date with the new regions :-(

**Comment by gurneyalex** [comment]
travis build of 8.0 was recently greenified. can you rebase?

**Comment by fclementic2c** [comment]
:+1:

**Pull request merged**
