### PR TITLE
[15.0][MIG] chorus pro connector

### PR DESCRIPTION
**Pull request by alexis-via**
Depends on many other PR from OCA/edi and OCA/community-data-files.
As you can see on the Chorus Pro qualif website https://qualif.chorus-pro.gouv.fr/aife_qual it is down until January 10 2022, so I am currently unable to make tests. I'll make some tests as soon as the qualif website is back up and running.

### CODE REVIEW

**Comment by alexis-via** [comment]
Chorus Pro qualif is back up and running. I successfully sent my first invoice to Chorus Pro Qualif with #odoo v15.

**Comment by legalsylvain** [comment]
Nice ! Thanks !
Relaunching test.
/ocabot rebase

**Comment by legalsylvain** [comment]
@alexis-via could you rebase ? Don't have write access on akretion repo.

**Comment by alexis-via** [comment]
The branch is up-to-date with origin/15.0.
But it depends on many other PRs in OCA/community-data-files and OCA/edi (probably about 8 PRs).

**Comment by alexis-via** [comment]
Blocked by account_invoice_transmit_method

**Pull request merged**
