### PR TITLE
8.0 add modules l10n_fr_business_document_import + l10n_fr_ubl

### PR DESCRIPTION
**Pull request by alexis-via**
This is a small glue module between account_invoice_pdf_import (under review in this PR: https://github.com/OCA/account-invoicing/pull/122) and l10n_fr_siret.

### CODE REVIEW

**Comment by brother-bernard** [comment]
:+1: using this code in production

**Comment by sebnege** [comment]
+1: it works well, using it in production

**Comment by AlexandreFournier** [comment]
+1

**Comment by cdubuit** [comment]
:+1: using this PR in production

**Comment by gurneyalex** [comment]
can you rebase?

**Comment by alexis-via** [comment]
Due to the strong disagreement that took place in https://github.com/OCA/l10n-france/pull/63 and the lack of respect for my work in OCA/l10n-france, I decided to move this module l10n_fr_invoice_import to a new repository outside of the OCA. I will decide in the coming days the name and location of the new repository and I will announce it here.

**Comment by alexis-via** [comment]
rebased

**Comment by gurneyalex** [comment]
:+1:

**Pull request merged**
